[use-grammars]
only = [
  # 
  "rust", "c", "cpp", "nix",
  # 
  "go", "gomod", "gowork", "gotmpl",
  # 
  "python", "bash", "lua", "scheme", "sql",
  # 
  "php", "php-only",
  # 
  "html", "css", "scss", "javascript", "jsdoc", "typescript", "jsx", "vue", "svelte",
  # 
  "json", "jsonc", "json5", "toml", "yaml", "xml", "ini", "kdl", "ron",
  # 
  "gdscript", "godot-resource", "glsl", "wgsl", "gdshader",
  # 
  "git-config", "git-commit", "git-ignore", "git-rebase", "git-attributes", "sshclientconfig",
  # 
  "hosts", "env", "make", "cmake",
  # 
  "comment", "diff", "regex",
  # 
  "latex", "typst", "markdown", "markdown.inline", "task", "todotxt", "mail",
  # 
  "log", "glicol",
  # 
  "dot", "hurl", "http", "po", "fluent", "pest", "beancount", "slint",
]

[language-server.hx-lsp]
command = "hx-lsp"

# ------ typos lsp ------
# https://github.com/tekumara/typos-lsp
# https://github.com/crate-ci/typos
# Add _typos.toml enable
[language-server.typos-lsp]
command = "typos-lsp"
config.diagnosticSeverity = "Warning"

# ---------- c/cpp -----
[[language]]
name = "c"
auto-format = true
language-servers = ["clangd", "hx-lsp"]

[[language]]
name = "cpp"
language-servers = ["clangd", "hx-lsp"]
auto-format = true

# ---------- json -----
[[language]]
name = "json"
formatter = { command = "prettier", args = ["--write", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "jsonc"
formatter = { command = "prettier", args = ["--write", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

# ---------- nix -----
[[language]]
name = "nix"
language-servers = ["hx-lsp", "nil", "nixd"]

# ---------- rust -----
[[language]]
name = "rust"
language-servers = ["rust-analyzer", "hx-lsp", "typos-lsp"]

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ name = "binary", completion = "filename" }]
args = { program = "{0}", initCommands = [
  "command script import /home/Designers/.config/helix/scripts/lldb_vscode_rustc_primer.py",
] }

# ---------- golang ----------------
[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp", "hx-lsp", "typos-lsp"]

# [[language.debugger.templates]]
# name = "binary"
# request = "launch"
# completion = [ { name = "binary", completion = "filename" } ]
# args = { program = "{0}", initCommands = [ "command script import /home/erasin/.config/helix/scripts/lldb_vscode_rustc_primer.py" ] }
# -------- typescript -----------
[language-server.typescript-language-server.config]
hostInfo = "helix"
locale = "zh-CN"

[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
# includeInlayVariableTypeHintsWhenTypeMatchesName = true

[language-server.typescript-language-server.config.javascript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true

# --- svelte ---
[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "    " }
roots = ["package.json"]
language-servers = ["svelteserver", "tailwindcss-ls"]

# --- css ---
[[language]]
name = "css"
file-types = ["css", "scss", "less"]
language-servers = [
  "vscode-css-language-server",
  "emmet-language-server",
  "tailwindcss-ls",
]

# --- html ---
[[language]]
name = "html"
file-types = ["html", "xhtml"]
language-servers = [
  "vscode-html-language-server",
  "emmet-language-server",
  "tailwindcss-ls",
  "hx-lsp",
  "typos-lsp",
]

# --- vue ---
[[language]]
name = "vue"
indent = { tab-width = 4, unit = "    " }
language-servers = ["vuels", "tailwindcss-ls", "hx-lsp", "typos-lsp"]

# --- tsx ---
[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "    " }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "hx-lsp",
  "typos-lsp",
]

# --- jsx ---
[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "    " }
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "hx-lsp",
  "typos-lsp",
]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "hx-lsp",
  "typos-lsp",
]

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "hx-lsp",
  "typos-lsp",
]

[language-server.ruff-lsp]
command = "ruff-lsp"
args = ["--ignore", "E501", "E402"]

[[language]]
name = "python"
file-types = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  ".pythonstartup",
  ".pythonrc",
  "SConstruct",
  "mel",
]
roots = ["pyproject.toml", "pyrightconfig.json"]
formatter = { command = "ruff", args = ["format"] }
language-servers = ["pyright", "ruff-lsp", "hx-lsp", "typos-lsp"]
auto-format = true

# ------------ lua --------------

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "stylua", args = [] }

[language-server.lua-language-server]
args = ["--locale", "zh-cn"]

# https://luals.github.io/wiki/configuration/
[language-server.lua-language-server.config.Lua.hint]
enable = true
arrayIndex = "Enable"
setType = true
paramName = "All"
paramType = true
await = true

[language-server.lua-language-server.config.Lua.workspace]
library = [
  "${3rd}/love2d/library",
  "${3rd}/busted/library",
  "${3rd}/Defold/library",
]

[language-server.lua-language-server.config.Lua.runtime]
nonstandardSymbol = [
  "+=",
  "-=",
  "*=",
  "/=",
  "//=",
  "%=",
  "<<=",
  ">>=",
  "&=",
  "|=",
  "^=",
]

special = { "import" = "require" }

[[grammar]]
name = "lua"
# source = { git = "https://github.com/MunifTanjim/tree-sitter-lua", rev = "9668709211b2e683f27f414454a8b51bf0a6bda1" }
source = { git = "https://github.com/erasin/tree-sitter-lua", rev = "0158ad30769a3fcf7f40dcaaa94509023ff7fea6" }
# source = { path = "/home/erasin/Development/project/tree-sitter-lua", rev = "" }

# ----------- git ---------------

[[language]]
name = "git-commit"
soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "ini"
scope = "source.ini"
file-types = [
  "ini",
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = ".editorconfig" },
  { glob = "rclone.conf" },
  "properties",
  "cfg",
  "directory",
  "desktop",
]


# --- markdown ----
[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide", "hx-lsp", "typos-lsp"]
# 设定 zen-mode-like
text-width = 80
soft-wrap = { enable = true, wrap-at-text-width = true }

# ---- latex ----
[[language]]
name = "latex"
language-servers = ["texlab"]
text-width = 80
soft-wrap = { enable = true, wrap-at-text-width = true }

# ---- typst ----
[[language]]
name = "typst"
language-servers = ["typst-lsp", "hx-lsp", "typos-lsp"]
formatter = { command = "typst", args = ["c"] }
text-width = 80
soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "mail"
scope = "source.eml"
injection-regex = "mail"
file-types = ["eml"]
indent = { tab-width = 4, unit = "\t" }

[[grammar]]
name = "mail"
source = { git = "https://github.com/dagle/tree-sitter-mail", rev = "a668550628e9a76bcac4864864dd9d60c91be27f" }
